### ISSUE TITLE
boss install HashLoad/JSONBr-Horse 

### ISSUE THREAD

**Issue by luisnt** [HashLoad/JSONBr-Horse#1]
## boss install HashLoad/JSONBr-Horse 

> [INFO ] Processing module jsonbr-horse
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x90 pc=0x11f2626]
> 
> goroutine 1 [running, locked to thread]:
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xeda31961e, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:41 +0x66
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002201c0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc000220380, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002201c0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002202a0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002201c0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc000220620, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc000220540, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc000220380, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002202a0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002201c0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.processOthers({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xd8)
>         /home/runner/work/boss/boss/core/installer/core.go:95 +0x7f4
> github.com/hashload/boss/core/installer.EnsureDependencies({{0xc000212820, 0x4c}, {0xc00020e4c0, 0x20}, {0x1fe117d8, 0xeda31961e, 0x179bac0}, 0xc000222690}, 0xc0002200e0, 0x1)
>         /home/runner/work/boss/boss/core/installer/core.go:50 +0x19b
> github.com/hashload/boss/core/installer.DoInstall(0xc0002200e0, 0x60)
>         /home/runner/work/boss/boss/core/installer/core.go:27 +0x114
> github.com/hashload/boss/core/installer.LocalInstall({0xc000234260, 0xc000107d10, 0x1200ea3}, 0xc0002200e0, 0x4, 0x0)
>         /home/runner/work/boss/boss/core/installer/local.go:11 +0x67
> github.com/hashload/boss/core.InstallModules({0xc000234260, 0x1, 0x1}, 0x0, 0x0)
>         /home/runner/work/boss/boss/core/installer.go:26 +0x192
> github.com/hashload/boss/cmd.glob..func3(0x177c6e0, {0xc000234260, 0x1, 0x1})
>         /home/runner/work/boss/boss/cmd/install.go:24 +0x33
> github.com/spf13/cobra.(*Command).execute(0x177c6e0, {0xc000234210, 0x1, 0x1})
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x5f8
> github.com/spf13/cobra.(*Command).ExecuteC(0x177cbe0)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
> github.com/hashload/boss/cmd.Execute()
>         /home/runner/work/boss/boss/cmd/root.go:38 +0x14a
> main.main()
>         /home/runner/work/boss/boss/app.go:8 +0x17

**Comment by isaquepinheiro** [comment]
Corrigido, e testado nessa ultima atualização
